language: rust
sudo: false
rust:
- stable
- beta
- nightly
os: linux
matrix:
  allow_failures:
  - rust: beta
  - rust: nightly
  fast_finish: true
cache: cargo

script:
- cargo test --release
- python build.py

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: oftb.tar.gz
  skip_cleanup: true
  on:
    branch: master
    condition: $TRAVIS_RUST_VERSION = stable
    tags: true
