language: rust
sudo: false
rust:
- stable
- beta
- nightly
os:
- linux
- osx
matrix:
  allow_failures:
  - rust: nightly
  fast_finish: true
cache: cargo

before_install:
- command -v just >/dev/null || cargo install just

script:
- just all

before_deploy: cargo build --release
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: target/release/oftb
  skip_cleanup: true
  on:
    branch: master
    condition: $TRAVIS_RUST_VERSION = stable
    tags: true
