language: rust
rust:
  - stable
  - beta
  - nightly
os:
  - linux
  - osx
script:
  - cargo test
  - cargo build --release

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: target/release/oftb
  skip_cleanup: true
  on:
    tags: true
